apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-dogu-operator.fullname" . }}-controller-manager
  labels:
    app: ces
  {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-dogu-operator.fullname" . }}-controller-manager
  labels:
    app: ces
    control-plane: controller-manager
  {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      app: ces
      app.kubernetes.io/name: k8s-dogu-operator
      control-plane: controller-manager
    {{- include "k8s-dogu-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ces
        app.kubernetes.io/name: k8s-dogu-operator
        control-plane: controller-manager
      {{- include "k8s-dogu-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {{- toYaml .Values.controllerManager.kubeRbacProxy.resources | nindent
          10 }}
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: STAGE
          value: production
        - name: LOG_LEVEL
          value: debug
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOGU_REGISTRY_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: k8s-dogu-operator-dogu-registry
        - name: DOGU_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: k8s-dogu-operator-dogu-registry
        - name: DOGU_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: k8s-dogu-operator-dogu-registry
        - name: DOGU_REGISTRY_URLSCHEMA
          valueFrom:
            secretKeyRef:
              key: urlschema
              name: k8s-dogu-operator-dogu-registry
              optional: true
        - name: DOCKER_REGISTRY
          valueFrom:
            secretKeyRef:
              key: .dockerconfigjson
              name: k8s-dogu-operator-docker-registry
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "k8s-dogu-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10