apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-dogu-operator.fullname" . }}-metrics-reader
  labels:
    app: ces
  {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get