apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dogu-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    app: ces
    control-plane: controller-manager
  {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app: ces
    app.kubernetes.io/name: k8s-dogu-operator
    control-plane: controller-manager
  {{- include "k8s-dogu-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}