// Code generated by mockery v2.20.0. DO NOT EDIT.

package health

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockComponentManager is an autogenerated mock type for the ComponentManager type
type MockComponentManager struct {
	mock.Mock
}

type MockComponentManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentManager) EXPECT() *MockComponentManager_Expecter {
	return &MockComponentManager_Expecter{mock: &_m.Mock}
}

// UpdateComponentHealth provides a mock function with given fields: ctx, componentName, namespace
func (_m *MockComponentManager) UpdateComponentHealth(ctx context.Context, componentName string, namespace string) error {
	ret := _m.Called(ctx, componentName, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, componentName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentManager_UpdateComponentHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentHealth'
type MockComponentManager_UpdateComponentHealth_Call struct {
	*mock.Call
}

// UpdateComponentHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - componentName string
//   - namespace string
func (_e *MockComponentManager_Expecter) UpdateComponentHealth(ctx interface{}, componentName interface{}, namespace interface{}) *MockComponentManager_UpdateComponentHealth_Call {
	return &MockComponentManager_UpdateComponentHealth_Call{Call: _e.mock.On("UpdateComponentHealth", ctx, componentName, namespace)}
}

func (_c *MockComponentManager_UpdateComponentHealth_Call) Run(run func(ctx context.Context, componentName string, namespace string)) *MockComponentManager_UpdateComponentHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockComponentManager_UpdateComponentHealth_Call) Return(_a0 error) *MockComponentManager_UpdateComponentHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentManager_UpdateComponentHealth_Call) RunAndReturn(run func(context.Context, string, string) error) *MockComponentManager_UpdateComponentHealth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponentHealthWithVersion provides a mock function with given fields: ctx, componentName, namespace, version
func (_m *MockComponentManager) UpdateComponentHealthWithVersion(ctx context.Context, componentName string, namespace string, version string) error {
	ret := _m.Called(ctx, componentName, namespace, version)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, componentName, namespace, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentManager_UpdateComponentHealthWithVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentHealthWithVersion'
type MockComponentManager_UpdateComponentHealthWithVersion_Call struct {
	*mock.Call
}

// UpdateComponentHealthWithVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - componentName string
//   - namespace string
//   - version string
func (_e *MockComponentManager_Expecter) UpdateComponentHealthWithVersion(ctx interface{}, componentName interface{}, namespace interface{}, version interface{}) *MockComponentManager_UpdateComponentHealthWithVersion_Call {
	return &MockComponentManager_UpdateComponentHealthWithVersion_Call{Call: _e.mock.On("UpdateComponentHealthWithVersion", ctx, componentName, namespace, version)}
}

func (_c *MockComponentManager_UpdateComponentHealthWithVersion_Call) Run(run func(ctx context.Context, componentName string, namespace string, version string)) *MockComponentManager_UpdateComponentHealthWithVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockComponentManager_UpdateComponentHealthWithVersion_Call) Return(_a0 error) *MockComponentManager_UpdateComponentHealthWithVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentManager_UpdateComponentHealthWithVersion_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockComponentManager_UpdateComponentHealthWithVersion_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockComponentManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockComponentManager creates a new instance of MockComponentManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockComponentManager(t mockConstructorTestingTNewMockComponentManager) *MockComponentManager {
	mock := &MockComponentManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
