// Code generated by mockery v2.53.3. DO NOT EDIT.

package client

import mock "github.com/stretchr/testify/mock"

// MockRollBack is an autogenerated mock type for the RollBack type
type MockRollBack struct {
	mock.Mock
}

type MockRollBack_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRollBack) EXPECT() *MockRollBack_Expecter {
	return &MockRollBack_Expecter{mock: &_m.Mock}
}

// RollbackRelease provides a mock function with given fields: spec
func (_m *MockRollBack) RollbackRelease(spec *ChartSpec) error {
	ret := _m.Called(spec)

	if len(ret) == 0 {
		panic("no return value specified for RollbackRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*ChartSpec) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRollBack_RollbackRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackRelease'
type MockRollBack_RollbackRelease_Call struct {
	*mock.Call
}

// RollbackRelease is a helper method to define mock.On call
//   - spec *ChartSpec
func (_e *MockRollBack_Expecter) RollbackRelease(spec interface{}) *MockRollBack_RollbackRelease_Call {
	return &MockRollBack_RollbackRelease_Call{Call: _e.mock.On("RollbackRelease", spec)}
}

func (_c *MockRollBack_RollbackRelease_Call) Run(run func(spec *ChartSpec)) *MockRollBack_RollbackRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ChartSpec))
	})
	return _c
}

func (_c *MockRollBack_RollbackRelease_Call) Return(_a0 error) *MockRollBack_RollbackRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollBack_RollbackRelease_Call) RunAndReturn(run func(*ChartSpec) error) *MockRollBack_RollbackRelease_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRollBack creates a new instance of MockRollBack. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRollBack(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRollBack {
	mock := &MockRollBack{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
