// Code generated by mockery v2.53.3. DO NOT EDIT.

package client

import (
	mock "github.com/stretchr/testify/mock"
	getter "helm.sh/helm/v3/pkg/getter"
)

// mockValuesOptions is an autogenerated mock type for the valuesOptions type
type mockValuesOptions struct {
	mock.Mock
}

type mockValuesOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *mockValuesOptions) EXPECT() *mockValuesOptions_Expecter {
	return &mockValuesOptions_Expecter{mock: &_m.Mock}
}

// MergeValues provides a mock function with given fields: p
func (_m *mockValuesOptions) MergeValues(p getter.Providers) (map[string]interface{}, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for MergeValues")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(getter.Providers) (map[string]interface{}, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(getter.Providers) map[string]interface{}); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(getter.Providers) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockValuesOptions_MergeValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeValues'
type mockValuesOptions_MergeValues_Call struct {
	*mock.Call
}

// MergeValues is a helper method to define mock.On call
//   - p getter.Providers
func (_e *mockValuesOptions_Expecter) MergeValues(p interface{}) *mockValuesOptions_MergeValues_Call {
	return &mockValuesOptions_MergeValues_Call{Call: _e.mock.On("MergeValues", p)}
}

func (_c *mockValuesOptions_MergeValues_Call) Run(run func(p getter.Providers)) *mockValuesOptions_MergeValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(getter.Providers))
	})
	return _c
}

func (_c *mockValuesOptions_MergeValues_Call) Return(_a0 map[string]interface{}, _a1 error) *mockValuesOptions_MergeValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockValuesOptions_MergeValues_Call) RunAndReturn(run func(getter.Providers) (map[string]interface{}, error)) *mockValuesOptions_MergeValues_Call {
	_c.Call.Return(run)
	return _c
}

// newMockValuesOptions creates a new instance of mockValuesOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockValuesOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockValuesOptions {
	mock := &mockValuesOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
