---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  labels:
    app: ces
    app.kubernetes.io/name: k8s-component-operator
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"