apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-longhorn-rolebinding
  namespace: longhorn-system
  labels:
    app: ces
    app.kubernetes.io/name: k8s-component-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-component-operator-manager-longhorn-role
subjects:
- kind: ServiceAccount
  name: k8s-component-operator-controller-manager
  namespace: '{{ .Namespace }}'
