apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-longhorn-role
  namespace: longhorn-system
  labels:
    app: ces
    app.kubernetes.io/name: k8s-component-operator
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"