// Code generated by mockery v2.53.6. DO NOT EDIT.

package operator

import mock "github.com/stretchr/testify/mock"

// mockHelmClient is an autogenerated mock type for the helmClient type
type mockHelmClient struct {
	mock.Mock
}

type mockHelmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHelmClient) EXPECT() *mockHelmClient_Expecter {
	return &mockHelmClient_Expecter{mock: &_m.Mock}
}

// MarkReleaseAsFailed provides a mock function with given fields: name, description
func (_m *mockHelmClient) MarkReleaseAsFailed(name string, description string) error {
	ret := _m.Called(name, description)

	if len(ret) == 0 {
		panic("no return value specified for MarkReleaseAsFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockHelmClient_MarkReleaseAsFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReleaseAsFailed'
type mockHelmClient_MarkReleaseAsFailed_Call struct {
	*mock.Call
}

// MarkReleaseAsFailed is a helper method to define mock.On call
//   - name string
//   - description string
func (_e *mockHelmClient_Expecter) MarkReleaseAsFailed(name interface{}, description interface{}) *mockHelmClient_MarkReleaseAsFailed_Call {
	return &mockHelmClient_MarkReleaseAsFailed_Call{Call: _e.mock.On("MarkReleaseAsFailed", name, description)}
}

func (_c *mockHelmClient_MarkReleaseAsFailed_Call) Run(run func(name string, description string)) *mockHelmClient_MarkReleaseAsFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockHelmClient_MarkReleaseAsFailed_Call) Return(_a0 error) *mockHelmClient_MarkReleaseAsFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHelmClient_MarkReleaseAsFailed_Call) RunAndReturn(run func(string, string) error) *mockHelmClient_MarkReleaseAsFailed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHelmClient creates a new instance of mockHelmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHelmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHelmClient {
	mock := &mockHelmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
