// Code generated by mockery v2.20.0. DO NOT EDIT.

package helm

import (
	context "context"

	client "github.com/cloudogu/k8s-component-operator/pkg/helm/client"
	chart "helm.sh/helm/v3/pkg/chart"

	mock "github.com/stretchr/testify/mock"

	release "helm.sh/helm/v3/pkg/release"
)

// mockComponentHelmClient is an autogenerated mock type for the componentHelmClient type
type mockComponentHelmClient struct {
	mock.Mock
}

type mockComponentHelmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockComponentHelmClient) EXPECT() *mockComponentHelmClient_Expecter {
	return &mockComponentHelmClient_Expecter{mock: &_m.Mock}
}

// GetChart provides a mock function with given fields: ctx, chartSpec
func (_m *mockComponentHelmClient) GetChart(ctx context.Context, chartSpec *client.ChartSpec) (*chart.Chart, error) {
	ret := _m.Called(ctx, chartSpec)

	var r0 *chart.Chart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ChartSpec) (*chart.Chart, error)); ok {
		return rf(ctx, chartSpec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.ChartSpec) *chart.Chart); ok {
		r0 = rf(ctx, chartSpec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.Chart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.ChartSpec) error); ok {
		r1 = rf(ctx, chartSpec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockComponentHelmClient_GetChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChart'
type mockComponentHelmClient_GetChart_Call struct {
	*mock.Call
}

// GetChart is a helper method to define mock.On call
//   - ctx context.Context
//   - chartSpec *client.ChartSpec
func (_e *mockComponentHelmClient_Expecter) GetChart(ctx interface{}, chartSpec interface{}) *mockComponentHelmClient_GetChart_Call {
	return &mockComponentHelmClient_GetChart_Call{Call: _e.mock.On("GetChart", ctx, chartSpec)}
}

func (_c *mockComponentHelmClient_GetChart_Call) Run(run func(ctx context.Context, chartSpec *client.ChartSpec)) *mockComponentHelmClient_GetChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ChartSpec))
	})
	return _c
}

func (_c *mockComponentHelmClient_GetChart_Call) Return(_a0 *chart.Chart, _a1 error) *mockComponentHelmClient_GetChart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockComponentHelmClient_GetChart_Call) RunAndReturn(run func(context.Context, *client.ChartSpec) (*chart.Chart, error)) *mockComponentHelmClient_GetChart_Call {
	_c.Call.Return(run)
	return _c
}

// GetChartSpecValues provides a mock function with given fields: _a0
func (_m *mockComponentHelmClient) GetChartSpecValues(_a0 *client.ChartSpec) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.ChartSpec) (map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.ChartSpec) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*client.ChartSpec) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockComponentHelmClient_GetChartSpecValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChartSpecValues'
type mockComponentHelmClient_GetChartSpecValues_Call struct {
	*mock.Call
}

// GetChartSpecValues is a helper method to define mock.On call
//   - _a0 *client.ChartSpec
func (_e *mockComponentHelmClient_Expecter) GetChartSpecValues(_a0 interface{}) *mockComponentHelmClient_GetChartSpecValues_Call {
	return &mockComponentHelmClient_GetChartSpecValues_Call{Call: _e.mock.On("GetChartSpecValues", _a0)}
}

func (_c *mockComponentHelmClient_GetChartSpecValues_Call) Run(run func(_a0 *client.ChartSpec)) *mockComponentHelmClient_GetChartSpecValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.ChartSpec))
	})
	return _c
}

func (_c *mockComponentHelmClient_GetChartSpecValues_Call) Return(_a0 map[string]interface{}, _a1 error) *mockComponentHelmClient_GetChartSpecValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockComponentHelmClient_GetChartSpecValues_Call) RunAndReturn(run func(*client.ChartSpec) (map[string]interface{}, error)) *mockComponentHelmClient_GetChartSpecValues_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseValues provides a mock function with given fields: name, allValues
func (_m *mockComponentHelmClient) GetReleaseValues(name string, allValues bool) (map[string]interface{}, error) {
	ret := _m.Called(name, allValues)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (map[string]interface{}, error)); ok {
		return rf(name, allValues)
	}
	if rf, ok := ret.Get(0).(func(string, bool) map[string]interface{}); ok {
		r0 = rf(name, allValues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(name, allValues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockComponentHelmClient_GetReleaseValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseValues'
type mockComponentHelmClient_GetReleaseValues_Call struct {
	*mock.Call
}

// GetReleaseValues is a helper method to define mock.On call
//   - name string
//   - allValues bool
func (_e *mockComponentHelmClient_Expecter) GetReleaseValues(name interface{}, allValues interface{}) *mockComponentHelmClient_GetReleaseValues_Call {
	return &mockComponentHelmClient_GetReleaseValues_Call{Call: _e.mock.On("GetReleaseValues", name, allValues)}
}

func (_c *mockComponentHelmClient_GetReleaseValues_Call) Run(run func(name string, allValues bool)) *mockComponentHelmClient_GetReleaseValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *mockComponentHelmClient_GetReleaseValues_Call) Return(_a0 map[string]interface{}, _a1 error) *mockComponentHelmClient_GetReleaseValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockComponentHelmClient_GetReleaseValues_Call) RunAndReturn(run func(string, bool) (map[string]interface{}, error)) *mockComponentHelmClient_GetReleaseValues_Call {
	_c.Call.Return(run)
	return _c
}

// InstallOrUpgrade provides a mock function with given fields: ctx, _a1
func (_m *mockComponentHelmClient) InstallOrUpgrade(ctx context.Context, _a1 *client.ChartSpec) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ChartSpec) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockComponentHelmClient_InstallOrUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOrUpgrade'
type mockComponentHelmClient_InstallOrUpgrade_Call struct {
	*mock.Call
}

// InstallOrUpgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *client.ChartSpec
func (_e *mockComponentHelmClient_Expecter) InstallOrUpgrade(ctx interface{}, _a1 interface{}) *mockComponentHelmClient_InstallOrUpgrade_Call {
	return &mockComponentHelmClient_InstallOrUpgrade_Call{Call: _e.mock.On("InstallOrUpgrade", ctx, _a1)}
}

func (_c *mockComponentHelmClient_InstallOrUpgrade_Call) Run(run func(ctx context.Context, _a1 *client.ChartSpec)) *mockComponentHelmClient_InstallOrUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ChartSpec))
	})
	return _c
}

func (_c *mockComponentHelmClient_InstallOrUpgrade_Call) Return(_a0 error) *mockComponentHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockComponentHelmClient_InstallOrUpgrade_Call) RunAndReturn(run func(context.Context, *client.ChartSpec) error) *mockComponentHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeployedReleases provides a mock function with given fields:
func (_m *mockComponentHelmClient) ListDeployedReleases() ([]*release.Release, error) {
	ret := _m.Called()

	var r0 []*release.Release
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*release.Release, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*release.Release); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*release.Release)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockComponentHelmClient_ListDeployedReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeployedReleases'
type mockComponentHelmClient_ListDeployedReleases_Call struct {
	*mock.Call
}

// ListDeployedReleases is a helper method to define mock.On call
func (_e *mockComponentHelmClient_Expecter) ListDeployedReleases() *mockComponentHelmClient_ListDeployedReleases_Call {
	return &mockComponentHelmClient_ListDeployedReleases_Call{Call: _e.mock.On("ListDeployedReleases")}
}

func (_c *mockComponentHelmClient_ListDeployedReleases_Call) Run(run func()) *mockComponentHelmClient_ListDeployedReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockComponentHelmClient_ListDeployedReleases_Call) Return(_a0 []*release.Release, _a1 error) *mockComponentHelmClient_ListDeployedReleases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockComponentHelmClient_ListDeployedReleases_Call) RunAndReturn(run func() ([]*release.Release, error)) *mockComponentHelmClient_ListDeployedReleases_Call {
	_c.Call.Return(run)
	return _c
}

// SatisfiesDependencies provides a mock function with given fields: ctx, _a1
func (_m *mockComponentHelmClient) SatisfiesDependencies(ctx context.Context, _a1 *client.ChartSpec) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ChartSpec) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockComponentHelmClient_SatisfiesDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SatisfiesDependencies'
type mockComponentHelmClient_SatisfiesDependencies_Call struct {
	*mock.Call
}

// SatisfiesDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *client.ChartSpec
func (_e *mockComponentHelmClient_Expecter) SatisfiesDependencies(ctx interface{}, _a1 interface{}) *mockComponentHelmClient_SatisfiesDependencies_Call {
	return &mockComponentHelmClient_SatisfiesDependencies_Call{Call: _e.mock.On("SatisfiesDependencies", ctx, _a1)}
}

func (_c *mockComponentHelmClient_SatisfiesDependencies_Call) Run(run func(ctx context.Context, _a1 *client.ChartSpec)) *mockComponentHelmClient_SatisfiesDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ChartSpec))
	})
	return _c
}

func (_c *mockComponentHelmClient_SatisfiesDependencies_Call) Return(_a0 error) *mockComponentHelmClient_SatisfiesDependencies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockComponentHelmClient_SatisfiesDependencies_Call) RunAndReturn(run func(context.Context, *client.ChartSpec) error) *mockComponentHelmClient_SatisfiesDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// Uninstall provides a mock function with given fields: releaseName
func (_m *mockComponentHelmClient) Uninstall(releaseName string) error {
	ret := _m.Called(releaseName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(releaseName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockComponentHelmClient_Uninstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uninstall'
type mockComponentHelmClient_Uninstall_Call struct {
	*mock.Call
}

// Uninstall is a helper method to define mock.On call
//   - releaseName string
func (_e *mockComponentHelmClient_Expecter) Uninstall(releaseName interface{}) *mockComponentHelmClient_Uninstall_Call {
	return &mockComponentHelmClient_Uninstall_Call{Call: _e.mock.On("Uninstall", releaseName)}
}

func (_c *mockComponentHelmClient_Uninstall_Call) Run(run func(releaseName string)) *mockComponentHelmClient_Uninstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockComponentHelmClient_Uninstall_Call) Return(_a0 error) *mockComponentHelmClient_Uninstall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockComponentHelmClient_Uninstall_Call) RunAndReturn(run func(string) error) *mockComponentHelmClient_Uninstall_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockComponentHelmClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockComponentHelmClient creates a new instance of mockComponentHelmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockComponentHelmClient(t mockConstructorTestingTnewMockComponentHelmClient) *mockComponentHelmClient {
	mock := &mockComponentHelmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
