// Code generated by mockery v2.53.3. DO NOT EDIT.

package helm

import (
	context "context"

	v1 "github.com/cloudogu/k8s-component-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockConfigMapRefReader is an autogenerated mock type for the configMapRefReader type
type mockConfigMapRefReader struct {
	mock.Mock
}

type mockConfigMapRefReader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigMapRefReader) EXPECT() *mockConfigMapRefReader_Expecter {
	return &mockConfigMapRefReader_Expecter{mock: &_m.Mock}
}

// GetValues provides a mock function with given fields: ctx, configMapReference
func (_m *mockConfigMapRefReader) GetValues(ctx context.Context, configMapReference *v1.Reference) (string, error) {
	ret := _m.Called(ctx, configMapReference)

	if len(ret) == 0 {
		panic("no return value specified for GetValues")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Reference) (string, error)); ok {
		return rf(ctx, configMapReference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Reference) string); ok {
		r0 = rf(ctx, configMapReference)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Reference) error); ok {
		r1 = rf(ctx, configMapReference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigMapRefReader_GetValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValues'
type mockConfigMapRefReader_GetValues_Call struct {
	*mock.Call
}

// GetValues is a helper method to define mock.On call
//   - ctx context.Context
//   - configMapReference *v1.Reference
func (_e *mockConfigMapRefReader_Expecter) GetValues(ctx interface{}, configMapReference interface{}) *mockConfigMapRefReader_GetValues_Call {
	return &mockConfigMapRefReader_GetValues_Call{Call: _e.mock.On("GetValues", ctx, configMapReference)}
}

func (_c *mockConfigMapRefReader_GetValues_Call) Run(run func(ctx context.Context, configMapReference *v1.Reference)) *mockConfigMapRefReader_GetValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Reference))
	})
	return _c
}

func (_c *mockConfigMapRefReader_GetValues_Call) Return(_a0 string, _a1 error) *mockConfigMapRefReader_GetValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigMapRefReader_GetValues_Call) RunAndReturn(run func(context.Context, *v1.Reference) (string, error)) *mockConfigMapRefReader_GetValues_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigMapRefReader creates a new instance of mockConfigMapRefReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigMapRefReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigMapRefReader {
	mock := &mockConfigMapRefReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
