// Code generated by mockery v2.20.0. DO NOT EDIT.

package helm

import mock "github.com/stretchr/testify/mock"

// MockOciRepositoryConfig is an autogenerated mock type for the OciRepositoryConfig type
type MockOciRepositoryConfig struct {
	mock.Mock
}

type MockOciRepositoryConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOciRepositoryConfig) EXPECT() *MockOciRepositoryConfig_Expecter {
	return &MockOciRepositoryConfig_Expecter{mock: &_m.Mock}
}

// GetOciEndpoint provides a mock function with given fields:
func (_m *MockOciRepositoryConfig) GetOciEndpoint() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOciRepositoryConfig_GetOciEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOciEndpoint'
type MockOciRepositoryConfig_GetOciEndpoint_Call struct {
	*mock.Call
}

// GetOciEndpoint is a helper method to define mock.On call
func (_e *MockOciRepositoryConfig_Expecter) GetOciEndpoint() *MockOciRepositoryConfig_GetOciEndpoint_Call {
	return &MockOciRepositoryConfig_GetOciEndpoint_Call{Call: _e.mock.On("GetOciEndpoint")}
}

func (_c *MockOciRepositoryConfig_GetOciEndpoint_Call) Run(run func()) *MockOciRepositoryConfig_GetOciEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOciRepositoryConfig_GetOciEndpoint_Call) Return(_a0 string, _a1 error) *MockOciRepositoryConfig_GetOciEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOciRepositoryConfig_GetOciEndpoint_Call) RunAndReturn(run func() (string, error)) *MockOciRepositoryConfig_GetOciEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockOciRepositoryConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOciRepositoryConfig creates a new instance of MockOciRepositoryConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOciRepositoryConfig(t mockConstructorTestingTNewMockOciRepositoryConfig) *MockOciRepositoryConfig {
	mock := &MockOciRepositoryConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
