// Code generated by mockery v2.20.0. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockHealthManager is an autogenerated mock type for the healthManager type
type mockHealthManager struct {
	mock.Mock
}

type mockHealthManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHealthManager) EXPECT() *mockHealthManager_Expecter {
	return &mockHealthManager_Expecter{mock: &_m.Mock}
}

// UpdateComponentHealth provides a mock function with given fields: ctx, componentName, namespace
func (_m *mockHealthManager) UpdateComponentHealth(ctx context.Context, componentName string, namespace string) error {
	ret := _m.Called(ctx, componentName, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, componentName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockHealthManager_UpdateComponentHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentHealth'
type mockHealthManager_UpdateComponentHealth_Call struct {
	*mock.Call
}

// UpdateComponentHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - componentName string
//   - namespace string
func (_e *mockHealthManager_Expecter) UpdateComponentHealth(ctx interface{}, componentName interface{}, namespace interface{}) *mockHealthManager_UpdateComponentHealth_Call {
	return &mockHealthManager_UpdateComponentHealth_Call{Call: _e.mock.On("UpdateComponentHealth", ctx, componentName, namespace)}
}

func (_c *mockHealthManager_UpdateComponentHealth_Call) Run(run func(ctx context.Context, componentName string, namespace string)) *mockHealthManager_UpdateComponentHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockHealthManager_UpdateComponentHealth_Call) Return(_a0 error) *mockHealthManager_UpdateComponentHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHealthManager_UpdateComponentHealth_Call) RunAndReturn(run func(context.Context, string, string) error) *mockHealthManager_UpdateComponentHealth_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockHealthManager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockHealthManager creates a new instance of mockHealthManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockHealthManager(t mockConstructorTestingTnewMockHealthManager) *mockHealthManager {
	mock := &mockHealthManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
