// Code generated by mockery v2.20.0. DO NOT EDIT.

package controllers

import (
	context "context"

	v1 "github.com/cloudogu/k8s-component-operator/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockInstallManager is an autogenerated mock type for the InstallManager type
type MockInstallManager struct {
	mock.Mock
}

type MockInstallManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallManager) EXPECT() *MockInstallManager_Expecter {
	return &MockInstallManager_Expecter{mock: &_m.Mock}
}

// Install provides a mock function with given fields: ctx, component
func (_m *MockInstallManager) Install(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstallManager_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockInstallManager_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockInstallManager_Expecter) Install(ctx interface{}, component interface{}) *MockInstallManager_Install_Call {
	return &MockInstallManager_Install_Call{Call: _e.mock.On("Install", ctx, component)}
}

func (_c *MockInstallManager_Install_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockInstallManager_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockInstallManager_Install_Call) Return(_a0 error) *MockInstallManager_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstallManager_Install_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockInstallManager_Install_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockInstallManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInstallManager creates a new instance of MockInstallManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInstallManager(t mockConstructorTestingTNewMockInstallManager) *MockInstallManager {
	mock := &MockInstallManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
