// Code generated by mockery v2.20.0. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	release "helm.sh/helm/v3/pkg/release"

	v1 "github.com/cloudogu/k8s-component-operator/pkg/api/v1"
)

// MockHelmClient is an autogenerated mock type for the HelmClient type
type MockHelmClient struct {
	mock.Mock
}

type MockHelmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelmClient) EXPECT() *MockHelmClient_Expecter {
	return &MockHelmClient_Expecter{mock: &_m.Mock}
}

// InstallOrUpgrade provides a mock function with given fields: ctx, component
func (_m *MockHelmClient) InstallOrUpgrade(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHelmClient_InstallOrUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOrUpgrade'
type MockHelmClient_InstallOrUpgrade_Call struct {
	*mock.Call
}

// InstallOrUpgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockHelmClient_Expecter) InstallOrUpgrade(ctx interface{}, component interface{}) *MockHelmClient_InstallOrUpgrade_Call {
	return &MockHelmClient_InstallOrUpgrade_Call{Call: _e.mock.On("InstallOrUpgrade", ctx, component)}
}

func (_c *MockHelmClient_InstallOrUpgrade_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockHelmClient_InstallOrUpgrade_Call) Return(_a0 error) *MockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHelmClient_InstallOrUpgrade_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeployedReleases provides a mock function with given fields:
func (_m *MockHelmClient) ListDeployedReleases() ([]*release.Release, error) {
	ret := _m.Called()

	var r0 []*release.Release
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*release.Release, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*release.Release); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*release.Release)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHelmClient_ListDeployedReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeployedReleases'
type MockHelmClient_ListDeployedReleases_Call struct {
	*mock.Call
}

// ListDeployedReleases is a helper method to define mock.On call
func (_e *MockHelmClient_Expecter) ListDeployedReleases() *MockHelmClient_ListDeployedReleases_Call {
	return &MockHelmClient_ListDeployedReleases_Call{Call: _e.mock.On("ListDeployedReleases")}
}

func (_c *MockHelmClient_ListDeployedReleases_Call) Run(run func()) *MockHelmClient_ListDeployedReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHelmClient_ListDeployedReleases_Call) Return(_a0 []*release.Release, _a1 error) *MockHelmClient_ListDeployedReleases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHelmClient_ListDeployedReleases_Call) RunAndReturn(run func() ([]*release.Release, error)) *MockHelmClient_ListDeployedReleases_Call {
	_c.Call.Return(run)
	return _c
}

// SatisfiesDependencies provides a mock function with given fields: ctx, component
func (_m *MockHelmClient) SatisfiesDependencies(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHelmClient_SatisfiesDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SatisfiesDependencies'
type MockHelmClient_SatisfiesDependencies_Call struct {
	*mock.Call
}

// SatisfiesDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockHelmClient_Expecter) SatisfiesDependencies(ctx interface{}, component interface{}) *MockHelmClient_SatisfiesDependencies_Call {
	return &MockHelmClient_SatisfiesDependencies_Call{Call: _e.mock.On("SatisfiesDependencies", ctx, component)}
}

func (_c *MockHelmClient_SatisfiesDependencies_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockHelmClient_SatisfiesDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockHelmClient_SatisfiesDependencies_Call) Return(_a0 error) *MockHelmClient_SatisfiesDependencies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHelmClient_SatisfiesDependencies_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockHelmClient_SatisfiesDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// Uninstall provides a mock function with given fields: component
func (_m *MockHelmClient) Uninstall(component *v1.Component) error {
	ret := _m.Called(component)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Component) error); ok {
		r0 = rf(component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHelmClient_Uninstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uninstall'
type MockHelmClient_Uninstall_Call struct {
	*mock.Call
}

// Uninstall is a helper method to define mock.On call
//   - component *v1.Component
func (_e *MockHelmClient_Expecter) Uninstall(component interface{}) *MockHelmClient_Uninstall_Call {
	return &MockHelmClient_Uninstall_Call{Call: _e.mock.On("Uninstall", component)}
}

func (_c *MockHelmClient_Uninstall_Call) Run(run func(component *v1.Component)) *MockHelmClient_Uninstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Component))
	})
	return _c
}

func (_c *MockHelmClient_Uninstall_Call) Return(_a0 error) *MockHelmClient_Uninstall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHelmClient_Uninstall_Call) RunAndReturn(run func(*v1.Component) error) *MockHelmClient_Uninstall_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockHelmClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHelmClient creates a new instance of MockHelmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHelmClient(t mockConstructorTestingTNewMockHelmClient) *MockHelmClient {
	mock := &MockHelmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
