// Code generated by mockery v2.20.0. DO NOT EDIT.

package controllers

import (
	context "context"

	v1 "github.com/cloudogu/k8s-component-operator/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockDeleteManager is an autogenerated mock type for the DeleteManager type
type MockDeleteManager struct {
	mock.Mock
}

type MockDeleteManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteManager) EXPECT() *MockDeleteManager_Expecter {
	return &MockDeleteManager_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, component
func (_m *MockDeleteManager) Delete(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleteManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockDeleteManager_Expecter) Delete(ctx interface{}, component interface{}) *MockDeleteManager_Delete_Call {
	return &MockDeleteManager_Delete_Call{Call: _e.mock.On("Delete", ctx, component)}
}

func (_c *MockDeleteManager_Delete_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockDeleteManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockDeleteManager_Delete_Call) Return(_a0 error) *MockDeleteManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteManager_Delete_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockDeleteManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockDeleteManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDeleteManager creates a new instance of MockDeleteManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDeleteManager(t mockConstructorTestingTNewMockDeleteManager) *MockDeleteManager {
	mock := &MockDeleteManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
