// Code generated by mockery v2.42.1. DO NOT EDIT.

package controllers

import (
	context "context"

	v1 "github.com/cloudogu/k8s-component-operator/pkg/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockComponentManager is an autogenerated mock type for the ComponentManager type
type MockComponentManager struct {
	mock.Mock
}

type MockComponentManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentManager) EXPECT() *MockComponentManager_Expecter {
	return &MockComponentManager_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, component
func (_m *MockComponentManager) Delete(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockComponentManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockComponentManager_Expecter) Delete(ctx interface{}, component interface{}) *MockComponentManager_Delete_Call {
	return &MockComponentManager_Delete_Call{Call: _e.mock.On("Delete", ctx, component)}
}

func (_c *MockComponentManager_Delete_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockComponentManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockComponentManager_Delete_Call) Return(_a0 error) *MockComponentManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentManager_Delete_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockComponentManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function with given fields: ctx, component
func (_m *MockComponentManager) Install(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentManager_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockComponentManager_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockComponentManager_Expecter) Install(ctx interface{}, component interface{}) *MockComponentManager_Install_Call {
	return &MockComponentManager_Install_Call{Call: _e.mock.On("Install", ctx, component)}
}

func (_c *MockComponentManager_Install_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockComponentManager_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockComponentManager_Install_Call) Return(_a0 error) *MockComponentManager_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentManager_Install_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockComponentManager_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Upgrade provides a mock function with given fields: ctx, component
func (_m *MockComponentManager) Upgrade(ctx context.Context, component *v1.Component) error {
	ret := _m.Called(ctx, component)

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Component) error); ok {
		r0 = rf(ctx, component)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentManager_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type MockComponentManager_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - component *v1.Component
func (_e *MockComponentManager_Expecter) Upgrade(ctx interface{}, component interface{}) *MockComponentManager_Upgrade_Call {
	return &MockComponentManager_Upgrade_Call{Call: _e.mock.On("Upgrade", ctx, component)}
}

func (_c *MockComponentManager_Upgrade_Call) Run(run func(ctx context.Context, component *v1.Component)) *MockComponentManager_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Component))
	})
	return _c
}

func (_c *MockComponentManager_Upgrade_Call) Return(_a0 error) *MockComponentManager_Upgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentManager_Upgrade_Call) RunAndReturn(run func(context.Context, *v1.Component) error) *MockComponentManager_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentManager creates a new instance of MockComponentManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentManager {
	mock := &MockComponentManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
