// Code generated by mockery v2.20.0. DO NOT EDIT.

package yaml

import mock "github.com/stretchr/testify/mock"

// mockDecoder is an autogenerated mock type for the decoder type
type mockDecoder struct {
	mock.Mock
}

type mockDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDecoder) EXPECT() *mockDecoder_Expecter {
	return &mockDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: into
func (_m *mockDecoder) Decode(into interface{}) error {
	ret := _m.Called(into)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(into)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type mockDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - into interface{}
func (_e *mockDecoder_Expecter) Decode(into interface{}) *mockDecoder_Decode_Call {
	return &mockDecoder_Decode_Call{Call: _e.mock.On("Decode", into)}
}

func (_c *mockDecoder_Decode_Call) Run(run func(into interface{})) *mockDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *mockDecoder_Decode_Call) Return(_a0 error) *mockDecoder_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDecoder_Decode_Call) RunAndReturn(run func(interface{}) error) *mockDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockDecoder interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDecoder creates a new instance of mockDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDecoder(t mockConstructorTestingTnewMockDecoder) *mockDecoder {
	mock := &mockDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
