# The k8s-component-operator must be abel to install all components using Helm.
# Since those components contain all kinds of resources
# the k8s-component-operator needs permissions to manage all these resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-component-operator.name" . }}-manager-role
  labels:
    {{- include "k8s-component-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-component-operator.name" . }}-manager-rolebinding
  labels:
    {{- include "k8s-component-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-component-operator.name" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-component-operator.name" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
