// Code generated by mockery v2.20.0. DO NOT EDIT.

package ecosystem

import mock "github.com/stretchr/testify/mock"

// MockComponentV1Alpha1Interface is an autogenerated mock type for the ComponentV1Alpha1Interface type
type MockComponentV1Alpha1Interface struct {
	mock.Mock
}

type MockComponentV1Alpha1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentV1Alpha1Interface) EXPECT() *MockComponentV1Alpha1Interface_Expecter {
	return &MockComponentV1Alpha1Interface_Expecter{mock: &_m.Mock}
}

// Components provides a mock function with given fields: namespace
func (_m *MockComponentV1Alpha1Interface) Components(namespace string) ComponentInterface {
	ret := _m.Called(namespace)

	var r0 ComponentInterface
	if rf, ok := ret.Get(0).(func(string) ComponentInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ComponentInterface)
		}
	}

	return r0
}

// MockComponentV1Alpha1Interface_Components_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Components'
type MockComponentV1Alpha1Interface_Components_Call struct {
	*mock.Call
}

// Components is a helper method to define mock.On call
//   - namespace string
func (_e *MockComponentV1Alpha1Interface_Expecter) Components(namespace interface{}) *MockComponentV1Alpha1Interface_Components_Call {
	return &MockComponentV1Alpha1Interface_Components_Call{Call: _e.mock.On("Components", namespace)}
}

func (_c *MockComponentV1Alpha1Interface_Components_Call) Run(run func(namespace string)) *MockComponentV1Alpha1Interface_Components_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockComponentV1Alpha1Interface_Components_Call) Return(_a0 ComponentInterface) *MockComponentV1Alpha1Interface_Components_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentV1Alpha1Interface_Components_Call) RunAndReturn(run func(string) ComponentInterface) *MockComponentV1Alpha1Interface_Components_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockComponentV1Alpha1Interface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockComponentV1Alpha1Interface creates a new instance of MockComponentV1Alpha1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockComponentV1Alpha1Interface(t mockConstructorTestingTNewMockComponentV1Alpha1Interface) *MockComponentV1Alpha1Interface {
	mock := &MockComponentV1Alpha1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
