// Code generated by mockery v2.20.0. DO NOT EDIT.

package ecosystem

import (
	apiserverinternalv1alpha1 "k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1"
	appsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"

	appsv1beta1 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"

	authenticationv1 "k8s.io/client-go/kubernetes/typed/authentication/v1"

	authenticationv1alpha1 "k8s.io/client-go/kubernetes/typed/authentication/v1alpha1"

	authenticationv1beta1 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"

	authorizationv1 "k8s.io/client-go/kubernetes/typed/authorization/v1"

	authorizationv1beta1 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"

	autoscalingv1 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"

	batchv1 "k8s.io/client-go/kubernetes/typed/batch/v1"

	batchv1beta1 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"

	certificatesv1 "k8s.io/client-go/kubernetes/typed/certificates/v1"

	certificatesv1alpha1 "k8s.io/client-go/kubernetes/typed/certificates/v1alpha1"

	certificatesv1beta1 "k8s.io/client-go/kubernetes/typed/certificates/v1beta1"

	coordinationv1 "k8s.io/client-go/kubernetes/typed/coordination/v1"

	coordinationv1beta1 "k8s.io/client-go/kubernetes/typed/coordination/v1beta1"

	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"

	discovery "k8s.io/client-go/discovery"

	discoveryv1 "k8s.io/client-go/kubernetes/typed/discovery/v1"

	discoveryv1beta1 "k8s.io/client-go/kubernetes/typed/discovery/v1beta1"

	eventsv1 "k8s.io/client-go/kubernetes/typed/events/v1"

	eventsv1beta1 "k8s.io/client-go/kubernetes/typed/events/v1beta1"

	extensionsv1beta1 "k8s.io/client-go/kubernetes/typed/extensions/v1beta1"

	flowcontrolv1 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1"

	flowcontrolv1beta1 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1"

	flowcontrolv1beta2 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2"

	mock "github.com/stretchr/testify/mock"

	networkingv1 "k8s.io/client-go/kubernetes/typed/networking/v1"

	networkingv1alpha1 "k8s.io/client-go/kubernetes/typed/networking/v1alpha1"

	networkingv1beta1 "k8s.io/client-go/kubernetes/typed/networking/v1beta1"

	nodev1 "k8s.io/client-go/kubernetes/typed/node/v1"

	nodev1alpha1 "k8s.io/client-go/kubernetes/typed/node/v1alpha1"

	nodev1beta1 "k8s.io/client-go/kubernetes/typed/node/v1beta1"

	policyv1 "k8s.io/client-go/kubernetes/typed/policy/v1"

	policyv1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"

	rbacv1 "k8s.io/client-go/kubernetes/typed/rbac/v1"

	rbacv1alpha1 "k8s.io/client-go/kubernetes/typed/rbac/v1alpha1"

	rbacv1beta1 "k8s.io/client-go/kubernetes/typed/rbac/v1beta1"

	schedulingv1 "k8s.io/client-go/kubernetes/typed/scheduling/v1"

	schedulingv1alpha1 "k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1"

	schedulingv1beta1 "k8s.io/client-go/kubernetes/typed/scheduling/v1beta1"

	storagev1 "k8s.io/client-go/kubernetes/typed/storage/v1"

	storagev1alpha1 "k8s.io/client-go/kubernetes/typed/storage/v1alpha1"

	storagev1beta1 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"

	v1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"

	v1alpha1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1"

	v1alpha2 "k8s.io/client-go/kubernetes/typed/resource/v1alpha2"

	v1beta1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1"

	v1beta2 "k8s.io/client-go/kubernetes/typed/apps/v1beta2"

	v1beta3 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3"

	v2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2"

	v2beta1 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1"

	v2beta2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
)

// MockComponentEcosystemInterface is an autogenerated mock type for the ComponentEcosystemInterface type
type MockComponentEcosystemInterface struct {
	mock.Mock
}

type MockComponentEcosystemInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentEcosystemInterface) EXPECT() *MockComponentEcosystemInterface_Expecter {
	return &MockComponentEcosystemInterface_Expecter{mock: &_m.Mock}
}

// AdmissionregistrationV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AdmissionregistrationV1() v1.AdmissionregistrationV1Interface {
	ret := _m.Called()

	var r0 v1.AdmissionregistrationV1Interface
	if rf, ok := ret.Get(0).(func() v1.AdmissionregistrationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.AdmissionregistrationV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AdmissionregistrationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1'
type MockComponentEcosystemInterface_AdmissionregistrationV1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AdmissionregistrationV1() *MockComponentEcosystemInterface_AdmissionregistrationV1_Call {
	return &MockComponentEcosystemInterface_AdmissionregistrationV1_Call{Call: _e.mock.On("AdmissionregistrationV1")}
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1_Call) Run(run func()) *MockComponentEcosystemInterface_AdmissionregistrationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1_Call) Return(_a0 v1.AdmissionregistrationV1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1_Call) RunAndReturn(run func() v1.AdmissionregistrationV1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AdmissionregistrationV1alpha1() v1alpha1.AdmissionregistrationV1alpha1Interface {
	ret := _m.Called()

	var r0 v1alpha1.AdmissionregistrationV1alpha1Interface
	if rf, ok := ret.Get(0).(func() v1alpha1.AdmissionregistrationV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.AdmissionregistrationV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1alpha1'
type MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AdmissionregistrationV1alpha1() *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call {
	return &MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call{Call: _e.mock.On("AdmissionregistrationV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call) Return(_a0 v1alpha1.AdmissionregistrationV1alpha1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call) RunAndReturn(run func() v1alpha1.AdmissionregistrationV1alpha1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AdmissionregistrationV1beta1() v1beta1.AdmissionregistrationV1beta1Interface {
	ret := _m.Called()

	var r0 v1beta1.AdmissionregistrationV1beta1Interface
	if rf, ok := ret.Get(0).(func() v1beta1.AdmissionregistrationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.AdmissionregistrationV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1beta1'
type MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AdmissionregistrationV1beta1() *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call {
	return &MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call{Call: _e.mock.On("AdmissionregistrationV1beta1")}
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call) Return(_a0 v1beta1.AdmissionregistrationV1beta1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call) RunAndReturn(run func() v1beta1.AdmissionregistrationV1beta1Interface) *MockComponentEcosystemInterface_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AppsV1() appsv1.AppsV1Interface {
	ret := _m.Called()

	var r0 appsv1.AppsV1Interface
	if rf, ok := ret.Get(0).(func() appsv1.AppsV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appsv1.AppsV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AppsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1'
type MockComponentEcosystemInterface_AppsV1_Call struct {
	*mock.Call
}

// AppsV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AppsV1() *MockComponentEcosystemInterface_AppsV1_Call {
	return &MockComponentEcosystemInterface_AppsV1_Call{Call: _e.mock.On("AppsV1")}
}

func (_c *MockComponentEcosystemInterface_AppsV1_Call) Run(run func()) *MockComponentEcosystemInterface_AppsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1_Call) Return(_a0 appsv1.AppsV1Interface) *MockComponentEcosystemInterface_AppsV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1_Call) RunAndReturn(run func() appsv1.AppsV1Interface) *MockComponentEcosystemInterface_AppsV1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AppsV1beta1() appsv1beta1.AppsV1beta1Interface {
	ret := _m.Called()

	var r0 appsv1beta1.AppsV1beta1Interface
	if rf, ok := ret.Get(0).(func() appsv1beta1.AppsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appsv1beta1.AppsV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AppsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta1'
type MockComponentEcosystemInterface_AppsV1beta1_Call struct {
	*mock.Call
}

// AppsV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AppsV1beta1() *MockComponentEcosystemInterface_AppsV1beta1_Call {
	return &MockComponentEcosystemInterface_AppsV1beta1_Call{Call: _e.mock.On("AppsV1beta1")}
}

func (_c *MockComponentEcosystemInterface_AppsV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_AppsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1beta1_Call) Return(_a0 appsv1beta1.AppsV1beta1Interface) *MockComponentEcosystemInterface_AppsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1beta1_Call) RunAndReturn(run func() appsv1beta1.AppsV1beta1Interface) *MockComponentEcosystemInterface_AppsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta2 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AppsV1beta2() v1beta2.AppsV1beta2Interface {
	ret := _m.Called()

	var r0 v1beta2.AppsV1beta2Interface
	if rf, ok := ret.Get(0).(func() v1beta2.AppsV1beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta2.AppsV1beta2Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AppsV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta2'
type MockComponentEcosystemInterface_AppsV1beta2_Call struct {
	*mock.Call
}

// AppsV1beta2 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AppsV1beta2() *MockComponentEcosystemInterface_AppsV1beta2_Call {
	return &MockComponentEcosystemInterface_AppsV1beta2_Call{Call: _e.mock.On("AppsV1beta2")}
}

func (_c *MockComponentEcosystemInterface_AppsV1beta2_Call) Run(run func()) *MockComponentEcosystemInterface_AppsV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1beta2_Call) Return(_a0 v1beta2.AppsV1beta2Interface) *MockComponentEcosystemInterface_AppsV1beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AppsV1beta2_Call) RunAndReturn(run func() v1beta2.AppsV1beta2Interface) *MockComponentEcosystemInterface_AppsV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AuthenticationV1() authenticationv1.AuthenticationV1Interface {
	ret := _m.Called()

	var r0 authenticationv1.AuthenticationV1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1.AuthenticationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1.AuthenticationV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AuthenticationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1'
type MockComponentEcosystemInterface_AuthenticationV1_Call struct {
	*mock.Call
}

// AuthenticationV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AuthenticationV1() *MockComponentEcosystemInterface_AuthenticationV1_Call {
	return &MockComponentEcosystemInterface_AuthenticationV1_Call{Call: _e.mock.On("AuthenticationV1")}
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1_Call) Run(run func()) *MockComponentEcosystemInterface_AuthenticationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1_Call) Return(_a0 authenticationv1.AuthenticationV1Interface) *MockComponentEcosystemInterface_AuthenticationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1_Call) RunAndReturn(run func() authenticationv1.AuthenticationV1Interface) *MockComponentEcosystemInterface_AuthenticationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AuthenticationV1alpha1() authenticationv1alpha1.AuthenticationV1alpha1Interface {
	ret := _m.Called()

	var r0 authenticationv1alpha1.AuthenticationV1alpha1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1alpha1.AuthenticationV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1alpha1.AuthenticationV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AuthenticationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1alpha1'
type MockComponentEcosystemInterface_AuthenticationV1alpha1_Call struct {
	*mock.Call
}

// AuthenticationV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AuthenticationV1alpha1() *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call {
	return &MockComponentEcosystemInterface_AuthenticationV1alpha1_Call{Call: _e.mock.On("AuthenticationV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call) Return(_a0 authenticationv1alpha1.AuthenticationV1alpha1Interface) *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call) RunAndReturn(run func() authenticationv1alpha1.AuthenticationV1alpha1Interface) *MockComponentEcosystemInterface_AuthenticationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AuthenticationV1beta1() authenticationv1beta1.AuthenticationV1beta1Interface {
	ret := _m.Called()

	var r0 authenticationv1beta1.AuthenticationV1beta1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1beta1.AuthenticationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1beta1.AuthenticationV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AuthenticationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1beta1'
type MockComponentEcosystemInterface_AuthenticationV1beta1_Call struct {
	*mock.Call
}

// AuthenticationV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AuthenticationV1beta1() *MockComponentEcosystemInterface_AuthenticationV1beta1_Call {
	return &MockComponentEcosystemInterface_AuthenticationV1beta1_Call{Call: _e.mock.On("AuthenticationV1beta1")}
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_AuthenticationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1beta1_Call) Return(_a0 authenticationv1beta1.AuthenticationV1beta1Interface) *MockComponentEcosystemInterface_AuthenticationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthenticationV1beta1_Call) RunAndReturn(run func() authenticationv1beta1.AuthenticationV1beta1Interface) *MockComponentEcosystemInterface_AuthenticationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AuthorizationV1() authorizationv1.AuthorizationV1Interface {
	ret := _m.Called()

	var r0 authorizationv1.AuthorizationV1Interface
	if rf, ok := ret.Get(0).(func() authorizationv1.AuthorizationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authorizationv1.AuthorizationV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AuthorizationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1'
type MockComponentEcosystemInterface_AuthorizationV1_Call struct {
	*mock.Call
}

// AuthorizationV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AuthorizationV1() *MockComponentEcosystemInterface_AuthorizationV1_Call {
	return &MockComponentEcosystemInterface_AuthorizationV1_Call{Call: _e.mock.On("AuthorizationV1")}
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1_Call) Run(run func()) *MockComponentEcosystemInterface_AuthorizationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1_Call) Return(_a0 authorizationv1.AuthorizationV1Interface) *MockComponentEcosystemInterface_AuthorizationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1_Call) RunAndReturn(run func() authorizationv1.AuthorizationV1Interface) *MockComponentEcosystemInterface_AuthorizationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AuthorizationV1beta1() authorizationv1beta1.AuthorizationV1beta1Interface {
	ret := _m.Called()

	var r0 authorizationv1beta1.AuthorizationV1beta1Interface
	if rf, ok := ret.Get(0).(func() authorizationv1beta1.AuthorizationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authorizationv1beta1.AuthorizationV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AuthorizationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1beta1'
type MockComponentEcosystemInterface_AuthorizationV1beta1_Call struct {
	*mock.Call
}

// AuthorizationV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AuthorizationV1beta1() *MockComponentEcosystemInterface_AuthorizationV1beta1_Call {
	return &MockComponentEcosystemInterface_AuthorizationV1beta1_Call{Call: _e.mock.On("AuthorizationV1beta1")}
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_AuthorizationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1beta1_Call) Return(_a0 authorizationv1beta1.AuthorizationV1beta1Interface) *MockComponentEcosystemInterface_AuthorizationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AuthorizationV1beta1_Call) RunAndReturn(run func() authorizationv1beta1.AuthorizationV1beta1Interface) *MockComponentEcosystemInterface_AuthorizationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AutoscalingV1() autoscalingv1.AutoscalingV1Interface {
	ret := _m.Called()

	var r0 autoscalingv1.AutoscalingV1Interface
	if rf, ok := ret.Get(0).(func() autoscalingv1.AutoscalingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(autoscalingv1.AutoscalingV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AutoscalingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV1'
type MockComponentEcosystemInterface_AutoscalingV1_Call struct {
	*mock.Call
}

// AutoscalingV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AutoscalingV1() *MockComponentEcosystemInterface_AutoscalingV1_Call {
	return &MockComponentEcosystemInterface_AutoscalingV1_Call{Call: _e.mock.On("AutoscalingV1")}
}

func (_c *MockComponentEcosystemInterface_AutoscalingV1_Call) Run(run func()) *MockComponentEcosystemInterface_AutoscalingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV1_Call) Return(_a0 autoscalingv1.AutoscalingV1Interface) *MockComponentEcosystemInterface_AutoscalingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV1_Call) RunAndReturn(run func() autoscalingv1.AutoscalingV1Interface) *MockComponentEcosystemInterface_AutoscalingV1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AutoscalingV2() v2.AutoscalingV2Interface {
	ret := _m.Called()

	var r0 v2.AutoscalingV2Interface
	if rf, ok := ret.Get(0).(func() v2.AutoscalingV2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2.AutoscalingV2Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AutoscalingV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2'
type MockComponentEcosystemInterface_AutoscalingV2_Call struct {
	*mock.Call
}

// AutoscalingV2 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AutoscalingV2() *MockComponentEcosystemInterface_AutoscalingV2_Call {
	return &MockComponentEcosystemInterface_AutoscalingV2_Call{Call: _e.mock.On("AutoscalingV2")}
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2_Call) Run(run func()) *MockComponentEcosystemInterface_AutoscalingV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2_Call) Return(_a0 v2.AutoscalingV2Interface) *MockComponentEcosystemInterface_AutoscalingV2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2_Call) RunAndReturn(run func() v2.AutoscalingV2Interface) *MockComponentEcosystemInterface_AutoscalingV2_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AutoscalingV2beta1() v2beta1.AutoscalingV2beta1Interface {
	ret := _m.Called()

	var r0 v2beta1.AutoscalingV2beta1Interface
	if rf, ok := ret.Get(0).(func() v2beta1.AutoscalingV2beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta1.AutoscalingV2beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AutoscalingV2beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta1'
type MockComponentEcosystemInterface_AutoscalingV2beta1_Call struct {
	*mock.Call
}

// AutoscalingV2beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AutoscalingV2beta1() *MockComponentEcosystemInterface_AutoscalingV2beta1_Call {
	return &MockComponentEcosystemInterface_AutoscalingV2beta1_Call{Call: _e.mock.On("AutoscalingV2beta1")}
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta1_Call) Run(run func()) *MockComponentEcosystemInterface_AutoscalingV2beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta1_Call) Return(_a0 v2beta1.AutoscalingV2beta1Interface) *MockComponentEcosystemInterface_AutoscalingV2beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta1_Call) RunAndReturn(run func() v2beta1.AutoscalingV2beta1Interface) *MockComponentEcosystemInterface_AutoscalingV2beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta2 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) AutoscalingV2beta2() v2beta2.AutoscalingV2beta2Interface {
	ret := _m.Called()

	var r0 v2beta2.AutoscalingV2beta2Interface
	if rf, ok := ret.Get(0).(func() v2beta2.AutoscalingV2beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta2.AutoscalingV2beta2Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_AutoscalingV2beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta2'
type MockComponentEcosystemInterface_AutoscalingV2beta2_Call struct {
	*mock.Call
}

// AutoscalingV2beta2 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) AutoscalingV2beta2() *MockComponentEcosystemInterface_AutoscalingV2beta2_Call {
	return &MockComponentEcosystemInterface_AutoscalingV2beta2_Call{Call: _e.mock.On("AutoscalingV2beta2")}
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta2_Call) Run(run func()) *MockComponentEcosystemInterface_AutoscalingV2beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta2_Call) Return(_a0 v2beta2.AutoscalingV2beta2Interface) *MockComponentEcosystemInterface_AutoscalingV2beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_AutoscalingV2beta2_Call) RunAndReturn(run func() v2beta2.AutoscalingV2beta2Interface) *MockComponentEcosystemInterface_AutoscalingV2beta2_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) BatchV1() batchv1.BatchV1Interface {
	ret := _m.Called()

	var r0 batchv1.BatchV1Interface
	if rf, ok := ret.Get(0).(func() batchv1.BatchV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(batchv1.BatchV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_BatchV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1'
type MockComponentEcosystemInterface_BatchV1_Call struct {
	*mock.Call
}

// BatchV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) BatchV1() *MockComponentEcosystemInterface_BatchV1_Call {
	return &MockComponentEcosystemInterface_BatchV1_Call{Call: _e.mock.On("BatchV1")}
}

func (_c *MockComponentEcosystemInterface_BatchV1_Call) Run(run func()) *MockComponentEcosystemInterface_BatchV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_BatchV1_Call) Return(_a0 batchv1.BatchV1Interface) *MockComponentEcosystemInterface_BatchV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_BatchV1_Call) RunAndReturn(run func() batchv1.BatchV1Interface) *MockComponentEcosystemInterface_BatchV1_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) BatchV1beta1() batchv1beta1.BatchV1beta1Interface {
	ret := _m.Called()

	var r0 batchv1beta1.BatchV1beta1Interface
	if rf, ok := ret.Get(0).(func() batchv1beta1.BatchV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(batchv1beta1.BatchV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_BatchV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1beta1'
type MockComponentEcosystemInterface_BatchV1beta1_Call struct {
	*mock.Call
}

// BatchV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) BatchV1beta1() *MockComponentEcosystemInterface_BatchV1beta1_Call {
	return &MockComponentEcosystemInterface_BatchV1beta1_Call{Call: _e.mock.On("BatchV1beta1")}
}

func (_c *MockComponentEcosystemInterface_BatchV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_BatchV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_BatchV1beta1_Call) Return(_a0 batchv1beta1.BatchV1beta1Interface) *MockComponentEcosystemInterface_BatchV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_BatchV1beta1_Call) RunAndReturn(run func() batchv1beta1.BatchV1beta1Interface) *MockComponentEcosystemInterface_BatchV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CertificatesV1() certificatesv1.CertificatesV1Interface {
	ret := _m.Called()

	var r0 certificatesv1.CertificatesV1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1.CertificatesV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1.CertificatesV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CertificatesV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1'
type MockComponentEcosystemInterface_CertificatesV1_Call struct {
	*mock.Call
}

// CertificatesV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CertificatesV1() *MockComponentEcosystemInterface_CertificatesV1_Call {
	return &MockComponentEcosystemInterface_CertificatesV1_Call{Call: _e.mock.On("CertificatesV1")}
}

func (_c *MockComponentEcosystemInterface_CertificatesV1_Call) Run(run func()) *MockComponentEcosystemInterface_CertificatesV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1_Call) Return(_a0 certificatesv1.CertificatesV1Interface) *MockComponentEcosystemInterface_CertificatesV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1_Call) RunAndReturn(run func() certificatesv1.CertificatesV1Interface) *MockComponentEcosystemInterface_CertificatesV1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CertificatesV1alpha1() certificatesv1alpha1.CertificatesV1alpha1Interface {
	ret := _m.Called()

	var r0 certificatesv1alpha1.CertificatesV1alpha1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1alpha1.CertificatesV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1alpha1.CertificatesV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CertificatesV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1alpha1'
type MockComponentEcosystemInterface_CertificatesV1alpha1_Call struct {
	*mock.Call
}

// CertificatesV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CertificatesV1alpha1() *MockComponentEcosystemInterface_CertificatesV1alpha1_Call {
	return &MockComponentEcosystemInterface_CertificatesV1alpha1_Call{Call: _e.mock.On("CertificatesV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_CertificatesV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_CertificatesV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1alpha1_Call) Return(_a0 certificatesv1alpha1.CertificatesV1alpha1Interface) *MockComponentEcosystemInterface_CertificatesV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1alpha1_Call) RunAndReturn(run func() certificatesv1alpha1.CertificatesV1alpha1Interface) *MockComponentEcosystemInterface_CertificatesV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CertificatesV1beta1() certificatesv1beta1.CertificatesV1beta1Interface {
	ret := _m.Called()

	var r0 certificatesv1beta1.CertificatesV1beta1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1beta1.CertificatesV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1beta1.CertificatesV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CertificatesV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1beta1'
type MockComponentEcosystemInterface_CertificatesV1beta1_Call struct {
	*mock.Call
}

// CertificatesV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CertificatesV1beta1() *MockComponentEcosystemInterface_CertificatesV1beta1_Call {
	return &MockComponentEcosystemInterface_CertificatesV1beta1_Call{Call: _e.mock.On("CertificatesV1beta1")}
}

func (_c *MockComponentEcosystemInterface_CertificatesV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_CertificatesV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1beta1_Call) Return(_a0 certificatesv1beta1.CertificatesV1beta1Interface) *MockComponentEcosystemInterface_CertificatesV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CertificatesV1beta1_Call) RunAndReturn(run func() certificatesv1beta1.CertificatesV1beta1Interface) *MockComponentEcosystemInterface_CertificatesV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ComponentV1Alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) ComponentV1Alpha1() ComponentV1Alpha1Interface {
	ret := _m.Called()

	var r0 ComponentV1Alpha1Interface
	if rf, ok := ret.Get(0).(func() ComponentV1Alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ComponentV1Alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_ComponentV1Alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentV1Alpha1'
type MockComponentEcosystemInterface_ComponentV1Alpha1_Call struct {
	*mock.Call
}

// ComponentV1Alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) ComponentV1Alpha1() *MockComponentEcosystemInterface_ComponentV1Alpha1_Call {
	return &MockComponentEcosystemInterface_ComponentV1Alpha1_Call{Call: _e.mock.On("ComponentV1Alpha1")}
}

func (_c *MockComponentEcosystemInterface_ComponentV1Alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_ComponentV1Alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_ComponentV1Alpha1_Call) Return(_a0 ComponentV1Alpha1Interface) *MockComponentEcosystemInterface_ComponentV1Alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_ComponentV1Alpha1_Call) RunAndReturn(run func() ComponentV1Alpha1Interface) *MockComponentEcosystemInterface_ComponentV1Alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CoordinationV1() coordinationv1.CoordinationV1Interface {
	ret := _m.Called()

	var r0 coordinationv1.CoordinationV1Interface
	if rf, ok := ret.Get(0).(func() coordinationv1.CoordinationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinationv1.CoordinationV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CoordinationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1'
type MockComponentEcosystemInterface_CoordinationV1_Call struct {
	*mock.Call
}

// CoordinationV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CoordinationV1() *MockComponentEcosystemInterface_CoordinationV1_Call {
	return &MockComponentEcosystemInterface_CoordinationV1_Call{Call: _e.mock.On("CoordinationV1")}
}

func (_c *MockComponentEcosystemInterface_CoordinationV1_Call) Run(run func()) *MockComponentEcosystemInterface_CoordinationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CoordinationV1_Call) Return(_a0 coordinationv1.CoordinationV1Interface) *MockComponentEcosystemInterface_CoordinationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CoordinationV1_Call) RunAndReturn(run func() coordinationv1.CoordinationV1Interface) *MockComponentEcosystemInterface_CoordinationV1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CoordinationV1beta1() coordinationv1beta1.CoordinationV1beta1Interface {
	ret := _m.Called()

	var r0 coordinationv1beta1.CoordinationV1beta1Interface
	if rf, ok := ret.Get(0).(func() coordinationv1beta1.CoordinationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinationv1beta1.CoordinationV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CoordinationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1beta1'
type MockComponentEcosystemInterface_CoordinationV1beta1_Call struct {
	*mock.Call
}

// CoordinationV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CoordinationV1beta1() *MockComponentEcosystemInterface_CoordinationV1beta1_Call {
	return &MockComponentEcosystemInterface_CoordinationV1beta1_Call{Call: _e.mock.On("CoordinationV1beta1")}
}

func (_c *MockComponentEcosystemInterface_CoordinationV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_CoordinationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CoordinationV1beta1_Call) Return(_a0 coordinationv1beta1.CoordinationV1beta1Interface) *MockComponentEcosystemInterface_CoordinationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CoordinationV1beta1_Call) RunAndReturn(run func() coordinationv1beta1.CoordinationV1beta1Interface) *MockComponentEcosystemInterface_CoordinationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CoreV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) CoreV1() corev1.CoreV1Interface {
	ret := _m.Called()

	var r0 corev1.CoreV1Interface
	if rf, ok := ret.Get(0).(func() corev1.CoreV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1.CoreV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_CoreV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoreV1'
type MockComponentEcosystemInterface_CoreV1_Call struct {
	*mock.Call
}

// CoreV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) CoreV1() *MockComponentEcosystemInterface_CoreV1_Call {
	return &MockComponentEcosystemInterface_CoreV1_Call{Call: _e.mock.On("CoreV1")}
}

func (_c *MockComponentEcosystemInterface_CoreV1_Call) Run(run func()) *MockComponentEcosystemInterface_CoreV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_CoreV1_Call) Return(_a0 corev1.CoreV1Interface) *MockComponentEcosystemInterface_CoreV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_CoreV1_Call) RunAndReturn(run func() corev1.CoreV1Interface) *MockComponentEcosystemInterface_CoreV1_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type MockComponentEcosystemInterface_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) Discovery() *MockComponentEcosystemInterface_Discovery_Call {
	return &MockComponentEcosystemInterface_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *MockComponentEcosystemInterface_Discovery_Call) Run(run func()) *MockComponentEcosystemInterface_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_Discovery_Call) Return(_a0 discovery.DiscoveryInterface) *MockComponentEcosystemInterface_Discovery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_Discovery_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *MockComponentEcosystemInterface_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) DiscoveryV1() discoveryv1.DiscoveryV1Interface {
	ret := _m.Called()

	var r0 discoveryv1.DiscoveryV1Interface
	if rf, ok := ret.Get(0).(func() discoveryv1.DiscoveryV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discoveryv1.DiscoveryV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_DiscoveryV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1'
type MockComponentEcosystemInterface_DiscoveryV1_Call struct {
	*mock.Call
}

// DiscoveryV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) DiscoveryV1() *MockComponentEcosystemInterface_DiscoveryV1_Call {
	return &MockComponentEcosystemInterface_DiscoveryV1_Call{Call: _e.mock.On("DiscoveryV1")}
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1_Call) Run(run func()) *MockComponentEcosystemInterface_DiscoveryV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1_Call) Return(_a0 discoveryv1.DiscoveryV1Interface) *MockComponentEcosystemInterface_DiscoveryV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1_Call) RunAndReturn(run func() discoveryv1.DiscoveryV1Interface) *MockComponentEcosystemInterface_DiscoveryV1_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) DiscoveryV1beta1() discoveryv1beta1.DiscoveryV1beta1Interface {
	ret := _m.Called()

	var r0 discoveryv1beta1.DiscoveryV1beta1Interface
	if rf, ok := ret.Get(0).(func() discoveryv1beta1.DiscoveryV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discoveryv1beta1.DiscoveryV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_DiscoveryV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1beta1'
type MockComponentEcosystemInterface_DiscoveryV1beta1_Call struct {
	*mock.Call
}

// DiscoveryV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) DiscoveryV1beta1() *MockComponentEcosystemInterface_DiscoveryV1beta1_Call {
	return &MockComponentEcosystemInterface_DiscoveryV1beta1_Call{Call: _e.mock.On("DiscoveryV1beta1")}
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_DiscoveryV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1beta1_Call) Return(_a0 discoveryv1beta1.DiscoveryV1beta1Interface) *MockComponentEcosystemInterface_DiscoveryV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_DiscoveryV1beta1_Call) RunAndReturn(run func() discoveryv1beta1.DiscoveryV1beta1Interface) *MockComponentEcosystemInterface_DiscoveryV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) EventsV1() eventsv1.EventsV1Interface {
	ret := _m.Called()

	var r0 eventsv1.EventsV1Interface
	if rf, ok := ret.Get(0).(func() eventsv1.EventsV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eventsv1.EventsV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_EventsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1'
type MockComponentEcosystemInterface_EventsV1_Call struct {
	*mock.Call
}

// EventsV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) EventsV1() *MockComponentEcosystemInterface_EventsV1_Call {
	return &MockComponentEcosystemInterface_EventsV1_Call{Call: _e.mock.On("EventsV1")}
}

func (_c *MockComponentEcosystemInterface_EventsV1_Call) Run(run func()) *MockComponentEcosystemInterface_EventsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_EventsV1_Call) Return(_a0 eventsv1.EventsV1Interface) *MockComponentEcosystemInterface_EventsV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_EventsV1_Call) RunAndReturn(run func() eventsv1.EventsV1Interface) *MockComponentEcosystemInterface_EventsV1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) EventsV1beta1() eventsv1beta1.EventsV1beta1Interface {
	ret := _m.Called()

	var r0 eventsv1beta1.EventsV1beta1Interface
	if rf, ok := ret.Get(0).(func() eventsv1beta1.EventsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eventsv1beta1.EventsV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_EventsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1beta1'
type MockComponentEcosystemInterface_EventsV1beta1_Call struct {
	*mock.Call
}

// EventsV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) EventsV1beta1() *MockComponentEcosystemInterface_EventsV1beta1_Call {
	return &MockComponentEcosystemInterface_EventsV1beta1_Call{Call: _e.mock.On("EventsV1beta1")}
}

func (_c *MockComponentEcosystemInterface_EventsV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_EventsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_EventsV1beta1_Call) Return(_a0 eventsv1beta1.EventsV1beta1Interface) *MockComponentEcosystemInterface_EventsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_EventsV1beta1_Call) RunAndReturn(run func() eventsv1beta1.EventsV1beta1Interface) *MockComponentEcosystemInterface_EventsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ExtensionsV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) ExtensionsV1beta1() extensionsv1beta1.ExtensionsV1beta1Interface {
	ret := _m.Called()

	var r0 extensionsv1beta1.ExtensionsV1beta1Interface
	if rf, ok := ret.Get(0).(func() extensionsv1beta1.ExtensionsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(extensionsv1beta1.ExtensionsV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_ExtensionsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtensionsV1beta1'
type MockComponentEcosystemInterface_ExtensionsV1beta1_Call struct {
	*mock.Call
}

// ExtensionsV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) ExtensionsV1beta1() *MockComponentEcosystemInterface_ExtensionsV1beta1_Call {
	return &MockComponentEcosystemInterface_ExtensionsV1beta1_Call{Call: _e.mock.On("ExtensionsV1beta1")}
}

func (_c *MockComponentEcosystemInterface_ExtensionsV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_ExtensionsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_ExtensionsV1beta1_Call) Return(_a0 extensionsv1beta1.ExtensionsV1beta1Interface) *MockComponentEcosystemInterface_ExtensionsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_ExtensionsV1beta1_Call) RunAndReturn(run func() extensionsv1beta1.ExtensionsV1beta1Interface) *MockComponentEcosystemInterface_ExtensionsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) FlowcontrolV1() flowcontrolv1.FlowcontrolV1Interface {
	ret := _m.Called()

	var r0 flowcontrolv1.FlowcontrolV1Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1.FlowcontrolV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1.FlowcontrolV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_FlowcontrolV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1'
type MockComponentEcosystemInterface_FlowcontrolV1_Call struct {
	*mock.Call
}

// FlowcontrolV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) FlowcontrolV1() *MockComponentEcosystemInterface_FlowcontrolV1_Call {
	return &MockComponentEcosystemInterface_FlowcontrolV1_Call{Call: _e.mock.On("FlowcontrolV1")}
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1_Call) Run(run func()) *MockComponentEcosystemInterface_FlowcontrolV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1_Call) Return(_a0 flowcontrolv1.FlowcontrolV1Interface) *MockComponentEcosystemInterface_FlowcontrolV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1_Call) RunAndReturn(run func() flowcontrolv1.FlowcontrolV1Interface) *MockComponentEcosystemInterface_FlowcontrolV1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) FlowcontrolV1beta1() flowcontrolv1beta1.FlowcontrolV1beta1Interface {
	ret := _m.Called()

	var r0 flowcontrolv1beta1.FlowcontrolV1beta1Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1beta1.FlowcontrolV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1beta1.FlowcontrolV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_FlowcontrolV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta1'
type MockComponentEcosystemInterface_FlowcontrolV1beta1_Call struct {
	*mock.Call
}

// FlowcontrolV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) FlowcontrolV1beta1() *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call {
	return &MockComponentEcosystemInterface_FlowcontrolV1beta1_Call{Call: _e.mock.On("FlowcontrolV1beta1")}
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call) Return(_a0 flowcontrolv1beta1.FlowcontrolV1beta1Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call) RunAndReturn(run func() flowcontrolv1beta1.FlowcontrolV1beta1Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta2 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) FlowcontrolV1beta2() flowcontrolv1beta2.FlowcontrolV1beta2Interface {
	ret := _m.Called()

	var r0 flowcontrolv1beta2.FlowcontrolV1beta2Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1beta2.FlowcontrolV1beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1beta2.FlowcontrolV1beta2Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_FlowcontrolV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta2'
type MockComponentEcosystemInterface_FlowcontrolV1beta2_Call struct {
	*mock.Call
}

// FlowcontrolV1beta2 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) FlowcontrolV1beta2() *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call {
	return &MockComponentEcosystemInterface_FlowcontrolV1beta2_Call{Call: _e.mock.On("FlowcontrolV1beta2")}
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call) Run(run func()) *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call) Return(_a0 flowcontrolv1beta2.FlowcontrolV1beta2Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call) RunAndReturn(run func() flowcontrolv1beta2.FlowcontrolV1beta2Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta3 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) FlowcontrolV1beta3() v1beta3.FlowcontrolV1beta3Interface {
	ret := _m.Called()

	var r0 v1beta3.FlowcontrolV1beta3Interface
	if rf, ok := ret.Get(0).(func() v1beta3.FlowcontrolV1beta3Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta3.FlowcontrolV1beta3Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_FlowcontrolV1beta3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta3'
type MockComponentEcosystemInterface_FlowcontrolV1beta3_Call struct {
	*mock.Call
}

// FlowcontrolV1beta3 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) FlowcontrolV1beta3() *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call {
	return &MockComponentEcosystemInterface_FlowcontrolV1beta3_Call{Call: _e.mock.On("FlowcontrolV1beta3")}
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call) Run(run func()) *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call) Return(_a0 v1beta3.FlowcontrolV1beta3Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call) RunAndReturn(run func() v1beta3.FlowcontrolV1beta3Interface) *MockComponentEcosystemInterface_FlowcontrolV1beta3_Call {
	_c.Call.Return(run)
	return _c
}

// InternalV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) InternalV1alpha1() apiserverinternalv1alpha1.InternalV1alpha1Interface {
	ret := _m.Called()

	var r0 apiserverinternalv1alpha1.InternalV1alpha1Interface
	if rf, ok := ret.Get(0).(func() apiserverinternalv1alpha1.InternalV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiserverinternalv1alpha1.InternalV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_InternalV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalV1alpha1'
type MockComponentEcosystemInterface_InternalV1alpha1_Call struct {
	*mock.Call
}

// InternalV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) InternalV1alpha1() *MockComponentEcosystemInterface_InternalV1alpha1_Call {
	return &MockComponentEcosystemInterface_InternalV1alpha1_Call{Call: _e.mock.On("InternalV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_InternalV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_InternalV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_InternalV1alpha1_Call) Return(_a0 apiserverinternalv1alpha1.InternalV1alpha1Interface) *MockComponentEcosystemInterface_InternalV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_InternalV1alpha1_Call) RunAndReturn(run func() apiserverinternalv1alpha1.InternalV1alpha1Interface) *MockComponentEcosystemInterface_InternalV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NetworkingV1() networkingv1.NetworkingV1Interface {
	ret := _m.Called()

	var r0 networkingv1.NetworkingV1Interface
	if rf, ok := ret.Get(0).(func() networkingv1.NetworkingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1.NetworkingV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NetworkingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1'
type MockComponentEcosystemInterface_NetworkingV1_Call struct {
	*mock.Call
}

// NetworkingV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NetworkingV1() *MockComponentEcosystemInterface_NetworkingV1_Call {
	return &MockComponentEcosystemInterface_NetworkingV1_Call{Call: _e.mock.On("NetworkingV1")}
}

func (_c *MockComponentEcosystemInterface_NetworkingV1_Call) Run(run func()) *MockComponentEcosystemInterface_NetworkingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1_Call) Return(_a0 networkingv1.NetworkingV1Interface) *MockComponentEcosystemInterface_NetworkingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1_Call) RunAndReturn(run func() networkingv1.NetworkingV1Interface) *MockComponentEcosystemInterface_NetworkingV1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NetworkingV1alpha1() networkingv1alpha1.NetworkingV1alpha1Interface {
	ret := _m.Called()

	var r0 networkingv1alpha1.NetworkingV1alpha1Interface
	if rf, ok := ret.Get(0).(func() networkingv1alpha1.NetworkingV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1alpha1.NetworkingV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NetworkingV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1alpha1'
type MockComponentEcosystemInterface_NetworkingV1alpha1_Call struct {
	*mock.Call
}

// NetworkingV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NetworkingV1alpha1() *MockComponentEcosystemInterface_NetworkingV1alpha1_Call {
	return &MockComponentEcosystemInterface_NetworkingV1alpha1_Call{Call: _e.mock.On("NetworkingV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_NetworkingV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_NetworkingV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1alpha1_Call) Return(_a0 networkingv1alpha1.NetworkingV1alpha1Interface) *MockComponentEcosystemInterface_NetworkingV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1alpha1_Call) RunAndReturn(run func() networkingv1alpha1.NetworkingV1alpha1Interface) *MockComponentEcosystemInterface_NetworkingV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NetworkingV1beta1() networkingv1beta1.NetworkingV1beta1Interface {
	ret := _m.Called()

	var r0 networkingv1beta1.NetworkingV1beta1Interface
	if rf, ok := ret.Get(0).(func() networkingv1beta1.NetworkingV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1beta1.NetworkingV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NetworkingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1beta1'
type MockComponentEcosystemInterface_NetworkingV1beta1_Call struct {
	*mock.Call
}

// NetworkingV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NetworkingV1beta1() *MockComponentEcosystemInterface_NetworkingV1beta1_Call {
	return &MockComponentEcosystemInterface_NetworkingV1beta1_Call{Call: _e.mock.On("NetworkingV1beta1")}
}

func (_c *MockComponentEcosystemInterface_NetworkingV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_NetworkingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1beta1_Call) Return(_a0 networkingv1beta1.NetworkingV1beta1Interface) *MockComponentEcosystemInterface_NetworkingV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NetworkingV1beta1_Call) RunAndReturn(run func() networkingv1beta1.NetworkingV1beta1Interface) *MockComponentEcosystemInterface_NetworkingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NodeV1() nodev1.NodeV1Interface {
	ret := _m.Called()

	var r0 nodev1.NodeV1Interface
	if rf, ok := ret.Get(0).(func() nodev1.NodeV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1.NodeV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NodeV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1'
type MockComponentEcosystemInterface_NodeV1_Call struct {
	*mock.Call
}

// NodeV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NodeV1() *MockComponentEcosystemInterface_NodeV1_Call {
	return &MockComponentEcosystemInterface_NodeV1_Call{Call: _e.mock.On("NodeV1")}
}

func (_c *MockComponentEcosystemInterface_NodeV1_Call) Run(run func()) *MockComponentEcosystemInterface_NodeV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1_Call) Return(_a0 nodev1.NodeV1Interface) *MockComponentEcosystemInterface_NodeV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1_Call) RunAndReturn(run func() nodev1.NodeV1Interface) *MockComponentEcosystemInterface_NodeV1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NodeV1alpha1() nodev1alpha1.NodeV1alpha1Interface {
	ret := _m.Called()

	var r0 nodev1alpha1.NodeV1alpha1Interface
	if rf, ok := ret.Get(0).(func() nodev1alpha1.NodeV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1alpha1.NodeV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NodeV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1alpha1'
type MockComponentEcosystemInterface_NodeV1alpha1_Call struct {
	*mock.Call
}

// NodeV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NodeV1alpha1() *MockComponentEcosystemInterface_NodeV1alpha1_Call {
	return &MockComponentEcosystemInterface_NodeV1alpha1_Call{Call: _e.mock.On("NodeV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_NodeV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_NodeV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1alpha1_Call) Return(_a0 nodev1alpha1.NodeV1alpha1Interface) *MockComponentEcosystemInterface_NodeV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1alpha1_Call) RunAndReturn(run func() nodev1alpha1.NodeV1alpha1Interface) *MockComponentEcosystemInterface_NodeV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) NodeV1beta1() nodev1beta1.NodeV1beta1Interface {
	ret := _m.Called()

	var r0 nodev1beta1.NodeV1beta1Interface
	if rf, ok := ret.Get(0).(func() nodev1beta1.NodeV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1beta1.NodeV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_NodeV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1beta1'
type MockComponentEcosystemInterface_NodeV1beta1_Call struct {
	*mock.Call
}

// NodeV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) NodeV1beta1() *MockComponentEcosystemInterface_NodeV1beta1_Call {
	return &MockComponentEcosystemInterface_NodeV1beta1_Call{Call: _e.mock.On("NodeV1beta1")}
}

func (_c *MockComponentEcosystemInterface_NodeV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_NodeV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1beta1_Call) Return(_a0 nodev1beta1.NodeV1beta1Interface) *MockComponentEcosystemInterface_NodeV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_NodeV1beta1_Call) RunAndReturn(run func() nodev1beta1.NodeV1beta1Interface) *MockComponentEcosystemInterface_NodeV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) PolicyV1() policyv1.PolicyV1Interface {
	ret := _m.Called()

	var r0 policyv1.PolicyV1Interface
	if rf, ok := ret.Get(0).(func() policyv1.PolicyV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policyv1.PolicyV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_PolicyV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1'
type MockComponentEcosystemInterface_PolicyV1_Call struct {
	*mock.Call
}

// PolicyV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) PolicyV1() *MockComponentEcosystemInterface_PolicyV1_Call {
	return &MockComponentEcosystemInterface_PolicyV1_Call{Call: _e.mock.On("PolicyV1")}
}

func (_c *MockComponentEcosystemInterface_PolicyV1_Call) Run(run func()) *MockComponentEcosystemInterface_PolicyV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_PolicyV1_Call) Return(_a0 policyv1.PolicyV1Interface) *MockComponentEcosystemInterface_PolicyV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_PolicyV1_Call) RunAndReturn(run func() policyv1.PolicyV1Interface) *MockComponentEcosystemInterface_PolicyV1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) PolicyV1beta1() policyv1beta1.PolicyV1beta1Interface {
	ret := _m.Called()

	var r0 policyv1beta1.PolicyV1beta1Interface
	if rf, ok := ret.Get(0).(func() policyv1beta1.PolicyV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policyv1beta1.PolicyV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_PolicyV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1beta1'
type MockComponentEcosystemInterface_PolicyV1beta1_Call struct {
	*mock.Call
}

// PolicyV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) PolicyV1beta1() *MockComponentEcosystemInterface_PolicyV1beta1_Call {
	return &MockComponentEcosystemInterface_PolicyV1beta1_Call{Call: _e.mock.On("PolicyV1beta1")}
}

func (_c *MockComponentEcosystemInterface_PolicyV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_PolicyV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_PolicyV1beta1_Call) Return(_a0 policyv1beta1.PolicyV1beta1Interface) *MockComponentEcosystemInterface_PolicyV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_PolicyV1beta1_Call) RunAndReturn(run func() policyv1beta1.PolicyV1beta1Interface) *MockComponentEcosystemInterface_PolicyV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) RbacV1() rbacv1.RbacV1Interface {
	ret := _m.Called()

	var r0 rbacv1.RbacV1Interface
	if rf, ok := ret.Get(0).(func() rbacv1.RbacV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1.RbacV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_RbacV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1'
type MockComponentEcosystemInterface_RbacV1_Call struct {
	*mock.Call
}

// RbacV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) RbacV1() *MockComponentEcosystemInterface_RbacV1_Call {
	return &MockComponentEcosystemInterface_RbacV1_Call{Call: _e.mock.On("RbacV1")}
}

func (_c *MockComponentEcosystemInterface_RbacV1_Call) Run(run func()) *MockComponentEcosystemInterface_RbacV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1_Call) Return(_a0 rbacv1.RbacV1Interface) *MockComponentEcosystemInterface_RbacV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1_Call) RunAndReturn(run func() rbacv1.RbacV1Interface) *MockComponentEcosystemInterface_RbacV1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) RbacV1alpha1() rbacv1alpha1.RbacV1alpha1Interface {
	ret := _m.Called()

	var r0 rbacv1alpha1.RbacV1alpha1Interface
	if rf, ok := ret.Get(0).(func() rbacv1alpha1.RbacV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1alpha1.RbacV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_RbacV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1alpha1'
type MockComponentEcosystemInterface_RbacV1alpha1_Call struct {
	*mock.Call
}

// RbacV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) RbacV1alpha1() *MockComponentEcosystemInterface_RbacV1alpha1_Call {
	return &MockComponentEcosystemInterface_RbacV1alpha1_Call{Call: _e.mock.On("RbacV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_RbacV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_RbacV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1alpha1_Call) Return(_a0 rbacv1alpha1.RbacV1alpha1Interface) *MockComponentEcosystemInterface_RbacV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1alpha1_Call) RunAndReturn(run func() rbacv1alpha1.RbacV1alpha1Interface) *MockComponentEcosystemInterface_RbacV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) RbacV1beta1() rbacv1beta1.RbacV1beta1Interface {
	ret := _m.Called()

	var r0 rbacv1beta1.RbacV1beta1Interface
	if rf, ok := ret.Get(0).(func() rbacv1beta1.RbacV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1beta1.RbacV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_RbacV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1beta1'
type MockComponentEcosystemInterface_RbacV1beta1_Call struct {
	*mock.Call
}

// RbacV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) RbacV1beta1() *MockComponentEcosystemInterface_RbacV1beta1_Call {
	return &MockComponentEcosystemInterface_RbacV1beta1_Call{Call: _e.mock.On("RbacV1beta1")}
}

func (_c *MockComponentEcosystemInterface_RbacV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_RbacV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1beta1_Call) Return(_a0 rbacv1beta1.RbacV1beta1Interface) *MockComponentEcosystemInterface_RbacV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_RbacV1beta1_Call) RunAndReturn(run func() rbacv1beta1.RbacV1beta1Interface) *MockComponentEcosystemInterface_RbacV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1alpha2 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) ResourceV1alpha2() v1alpha2.ResourceV1alpha2Interface {
	ret := _m.Called()

	var r0 v1alpha2.ResourceV1alpha2Interface
	if rf, ok := ret.Get(0).(func() v1alpha2.ResourceV1alpha2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha2.ResourceV1alpha2Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_ResourceV1alpha2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1alpha2'
type MockComponentEcosystemInterface_ResourceV1alpha2_Call struct {
	*mock.Call
}

// ResourceV1alpha2 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) ResourceV1alpha2() *MockComponentEcosystemInterface_ResourceV1alpha2_Call {
	return &MockComponentEcosystemInterface_ResourceV1alpha2_Call{Call: _e.mock.On("ResourceV1alpha2")}
}

func (_c *MockComponentEcosystemInterface_ResourceV1alpha2_Call) Run(run func()) *MockComponentEcosystemInterface_ResourceV1alpha2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_ResourceV1alpha2_Call) Return(_a0 v1alpha2.ResourceV1alpha2Interface) *MockComponentEcosystemInterface_ResourceV1alpha2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_ResourceV1alpha2_Call) RunAndReturn(run func() v1alpha2.ResourceV1alpha2Interface) *MockComponentEcosystemInterface_ResourceV1alpha2_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) SchedulingV1() schedulingv1.SchedulingV1Interface {
	ret := _m.Called()

	var r0 schedulingv1.SchedulingV1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1.SchedulingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1.SchedulingV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_SchedulingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1'
type MockComponentEcosystemInterface_SchedulingV1_Call struct {
	*mock.Call
}

// SchedulingV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) SchedulingV1() *MockComponentEcosystemInterface_SchedulingV1_Call {
	return &MockComponentEcosystemInterface_SchedulingV1_Call{Call: _e.mock.On("SchedulingV1")}
}

func (_c *MockComponentEcosystemInterface_SchedulingV1_Call) Run(run func()) *MockComponentEcosystemInterface_SchedulingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1_Call) Return(_a0 schedulingv1.SchedulingV1Interface) *MockComponentEcosystemInterface_SchedulingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1_Call) RunAndReturn(run func() schedulingv1.SchedulingV1Interface) *MockComponentEcosystemInterface_SchedulingV1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) SchedulingV1alpha1() schedulingv1alpha1.SchedulingV1alpha1Interface {
	ret := _m.Called()

	var r0 schedulingv1alpha1.SchedulingV1alpha1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1alpha1.SchedulingV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1alpha1.SchedulingV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_SchedulingV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1alpha1'
type MockComponentEcosystemInterface_SchedulingV1alpha1_Call struct {
	*mock.Call
}

// SchedulingV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) SchedulingV1alpha1() *MockComponentEcosystemInterface_SchedulingV1alpha1_Call {
	return &MockComponentEcosystemInterface_SchedulingV1alpha1_Call{Call: _e.mock.On("SchedulingV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_SchedulingV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_SchedulingV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1alpha1_Call) Return(_a0 schedulingv1alpha1.SchedulingV1alpha1Interface) *MockComponentEcosystemInterface_SchedulingV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1alpha1_Call) RunAndReturn(run func() schedulingv1alpha1.SchedulingV1alpha1Interface) *MockComponentEcosystemInterface_SchedulingV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) SchedulingV1beta1() schedulingv1beta1.SchedulingV1beta1Interface {
	ret := _m.Called()

	var r0 schedulingv1beta1.SchedulingV1beta1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1beta1.SchedulingV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1beta1.SchedulingV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_SchedulingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1beta1'
type MockComponentEcosystemInterface_SchedulingV1beta1_Call struct {
	*mock.Call
}

// SchedulingV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) SchedulingV1beta1() *MockComponentEcosystemInterface_SchedulingV1beta1_Call {
	return &MockComponentEcosystemInterface_SchedulingV1beta1_Call{Call: _e.mock.On("SchedulingV1beta1")}
}

func (_c *MockComponentEcosystemInterface_SchedulingV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_SchedulingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1beta1_Call) Return(_a0 schedulingv1beta1.SchedulingV1beta1Interface) *MockComponentEcosystemInterface_SchedulingV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_SchedulingV1beta1_Call) RunAndReturn(run func() schedulingv1beta1.SchedulingV1beta1Interface) *MockComponentEcosystemInterface_SchedulingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) StorageV1() storagev1.StorageV1Interface {
	ret := _m.Called()

	var r0 storagev1.StorageV1Interface
	if rf, ok := ret.Get(0).(func() storagev1.StorageV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1.StorageV1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_StorageV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1'
type MockComponentEcosystemInterface_StorageV1_Call struct {
	*mock.Call
}

// StorageV1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) StorageV1() *MockComponentEcosystemInterface_StorageV1_Call {
	return &MockComponentEcosystemInterface_StorageV1_Call{Call: _e.mock.On("StorageV1")}
}

func (_c *MockComponentEcosystemInterface_StorageV1_Call) Run(run func()) *MockComponentEcosystemInterface_StorageV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1_Call) Return(_a0 storagev1.StorageV1Interface) *MockComponentEcosystemInterface_StorageV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1_Call) RunAndReturn(run func() storagev1.StorageV1Interface) *MockComponentEcosystemInterface_StorageV1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1alpha1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) StorageV1alpha1() storagev1alpha1.StorageV1alpha1Interface {
	ret := _m.Called()

	var r0 storagev1alpha1.StorageV1alpha1Interface
	if rf, ok := ret.Get(0).(func() storagev1alpha1.StorageV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1alpha1.StorageV1alpha1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_StorageV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1alpha1'
type MockComponentEcosystemInterface_StorageV1alpha1_Call struct {
	*mock.Call
}

// StorageV1alpha1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) StorageV1alpha1() *MockComponentEcosystemInterface_StorageV1alpha1_Call {
	return &MockComponentEcosystemInterface_StorageV1alpha1_Call{Call: _e.mock.On("StorageV1alpha1")}
}

func (_c *MockComponentEcosystemInterface_StorageV1alpha1_Call) Run(run func()) *MockComponentEcosystemInterface_StorageV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1alpha1_Call) Return(_a0 storagev1alpha1.StorageV1alpha1Interface) *MockComponentEcosystemInterface_StorageV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1alpha1_Call) RunAndReturn(run func() storagev1alpha1.StorageV1alpha1Interface) *MockComponentEcosystemInterface_StorageV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1beta1 provides a mock function with given fields:
func (_m *MockComponentEcosystemInterface) StorageV1beta1() storagev1beta1.StorageV1beta1Interface {
	ret := _m.Called()

	var r0 storagev1beta1.StorageV1beta1Interface
	if rf, ok := ret.Get(0).(func() storagev1beta1.StorageV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1beta1.StorageV1beta1Interface)
		}
	}

	return r0
}

// MockComponentEcosystemInterface_StorageV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1beta1'
type MockComponentEcosystemInterface_StorageV1beta1_Call struct {
	*mock.Call
}

// StorageV1beta1 is a helper method to define mock.On call
func (_e *MockComponentEcosystemInterface_Expecter) StorageV1beta1() *MockComponentEcosystemInterface_StorageV1beta1_Call {
	return &MockComponentEcosystemInterface_StorageV1beta1_Call{Call: _e.mock.On("StorageV1beta1")}
}

func (_c *MockComponentEcosystemInterface_StorageV1beta1_Call) Run(run func()) *MockComponentEcosystemInterface_StorageV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1beta1_Call) Return(_a0 storagev1beta1.StorageV1beta1Interface) *MockComponentEcosystemInterface_StorageV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentEcosystemInterface_StorageV1beta1_Call) RunAndReturn(run func() storagev1beta1.StorageV1beta1Interface) *MockComponentEcosystemInterface_StorageV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockComponentEcosystemInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockComponentEcosystemInterface creates a new instance of MockComponentEcosystemInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockComponentEcosystemInterface(t mockConstructorTestingTNewMockComponentEcosystemInterface) *MockComponentEcosystemInterface {
	mock := &MockComponentEcosystemInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
